baseurl = "https://ashcoding.github.io/tgw-website/"
title = "Today Got What?"
languageCode = "en-us"
theme = "hugo-cactus-theme"

[params]
  name = "Today Got What?"
	description = "A curation of fun events in Singapore"
	bio = "Curating fun events in Singapore"
